version: "3.3"
services:
  resonite:
    image: shadowpanther/resonite-headless:latest
    container_name: resonite-headless
    tty: true
    stdin_open: true
    environment:
      STEAMBETA: headless
      STEAMBETAPASSWORD: CHANGEME
      STEAMLOGIN: "USER PASSWORD"
      # Set additional command line parameters for the headless like
      #CMD_OPTIONS: "-LoadAssembly ResoniteModLoader.dll"  
    volumes:
      - "./Config:/Config:ro"
      - "./Logs:/Logs"
      - "./Data:/home/steam/resonite-headless"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
